/**
 * `@pylos/core` — the Pylos kernel (KERNEL §9).
 *
 * The archive, the memory IR, the context compiler, the loss ledger, the pager
 * and the receipts. No UI dependency, fully testable headlessly.
 *
 * ```ts
 * const vault = openVault();
 * const thread = vault.threads.primary();
 * const result = await runTurn(vault, thread.id, { text, model, provider });
 * ```
 *
 * The browser-safe half is exported separately as `@pylos/core/pure`.
 */

export {
  ADDRESS_QUERY_DIGEST_VERSION,
  ADDRESS_ROUTE_LIST_LIMIT,
  type AddressAliasProposal,
  type AddressAliasResult,
  type AddressAliasRevalidation,
  type AddressAliasRow,
  type AddressReceiptRouteRecordInput,
  type AddressReuseResult,
  type AddressRevalidation,
  type AddressRouteRecordInput,
  type AddressRouteRow,
  type AddressRouteStatus,
  type AddressRouteView,
  type AddressRouteWriteResult,
  type AddressWitness,
  addressAliasFailure,
  addressInvalidationDigestOf,
  addressQueryDigest,
  addressRouteDigestOf,
  addressRouteRowBoundsFailure,
  addressWitnessFailure,
  canonicalAddressQuery,
  getAddressRoute,
  invalidateAddressRoute,
  invalidateAddressRoutesForSources,
  invalidateAddressRoutesForSourcesCount,
  listAddressAliases,
  listAddressRoutes,
  listCurrentAddressRoutes,
  listEffectiveAddressRoutes,
  normalizeAddressQuery,
  parseAddressAliasRow,
  parseAddressRouteRow,
  parseAddressWitness,
  proposeAddressAlias,
  recordAddressRoute,
  recordAddressRouteFromReceipt,
  reuseAddressRoute,
  revalidateAddressAlias,
  revalidateAddressRoute,
  verifyAliasPresence,
  witnessForEpisode,
} from "./address.ts";
export {
  type AtomizationReceipt,
  type AtomizeOptions,
  atomize,
  atomizeWithModel,
  authorityOf,
  MAX_MODEL_ATOM_CANDIDATES,
  MAX_MODEL_ATOM_EPISODES,
  MAX_RULE_ATOM_CANDIDATES,
  type ModelAtomCandidate,
  type ModelExtractor,
} from "./atomize.ts";
export {
  ATTACHMENT_CHUNK_SIZE,
  type AttachmentRangeRead,
  type AttachmentRangeReadOptions,
  type AttachmentSpanRead,
  type AttachmentSpanVerification,
  attachmentMetadataFailure,
  attachmentNameFromMeta,
  attachmentNameProbes,
  buildAttachmentManifest,
  isIndexableAttachment,
  legacyAttachmentManifest,
  MAX_ATTACHMENT_MIME_BYTES,
  MAX_ATTACHMENT_NAME_BYTES,
  manifestDigestOf,
  manifestPartitionValid,
  normalizeAttachmentName,
  readAttachmentRange,
  readAttachmentSpan,
  verifyAttachmentSpan,
} from "./attachment.ts";
export {
  type BlobDeletionEntry,
  type BlobDeletionStage,
  cleanupBlobDeletion,
  commitBlobDeletion,
  createBlobDeletion,
  discardBlobDeletion,
  type LiveBlobReferenceBatch,
  MAX_BLOB_DELETION_ENTRIES,
  MAX_BLOB_DELETION_ENTRIES_TOTAL,
  MAX_BLOB_DELETION_JOURNAL_BYTES,
  MAX_BLOB_DELETION_STAGES,
  recoverBlobDeletions,
  recoverBlobDeletionsBatched,
  stageBlobForDeletion,
} from "./blob-delete.ts";
export {
  BUNDLE_LIMITS,
  BUNDLE_READ_INACTIVITY_MS,
  BUNDLE_TRANSFER_DEADLINE_MS,
  BUNDLE_TRANSPORT_BUFFER_BOUND,
  type BundleLimits,
  type BundleManifest,
  type BundleProgress,
  type BundleProgressPhase,
  type ExportOptions,
  exportBundle,
  exportBundleStream,
  exportBundleV1,
  type ImportOptions,
  importBundle,
  importBundleStream,
} from "./bundle.ts";
export {
  answerReceiptDigestOf,
  CLAIM_GRAMMAR_VERSION,
  type ClaimMapEntry,
  type ClaimScanResult,
  claimScanDigestOf,
  type EvidenceSource,
  type GateInput,
  type GateResult,
  gateAnswer,
  isMemoryQuestion,
  issueEvidenceCapabilities,
  parseClaimMap,
  qualificationLinesFor,
  scanRememberedClaims,
  scanRememberedClaimsDetailed,
} from "./claim-gate.ts";
export {
  type CapsuleTokens,
  type CapsuleWriter,
  type CompactOptions,
  capsuleLedgerNames,
  capsuleTokensFor,
  compact,
  compactionPending,
  coveredTo,
  levelSpan,
  MAX_CAPSULE_WORK_PER_COMPACT,
  ROOT_LEVEL,
  residentCapsules,
  residentLeafCount,
  sourceNamesForRange,
  sourceNamesForRangeStream,
} from "./compact.ts";
export { type Compilation, type CompileOptions, compile, compileView } from "./compile.ts";
export {
  DEMO_ATTACHMENT_NAME,
  DEMO_BUDGET,
  DEMO_MODEL,
  DEMO_TAIL_MARKER,
  DEMO_VERSION,
  demo,
  readDemo,
} from "./demo.ts";
export {
  type ForgetResult,
  type ForgetTarget,
  forget,
  MAX_FORGET_DELETION_OBJECTS,
  MAX_FORGET_TARGETS,
} from "./forget.ts";
export { canonicalHash, chainHash, genesisHash, newId, sha256 } from "./hash.ts";
export {
  collectionCue,
  coverageFor,
  explicitCardinality,
  renderCoverage,
} from "./obligation.ts";
export {
  containsName,
  excerpt,
  isResident,
  type PageRequest,
  type PageResult,
  page,
  recall,
  resolves,
  TOKENS_PER_PAGE,
} from "./page.ts";
// The pure layer is re-exported for convenience; `@pylos/core/pure` is the
// browser-safe entry point that carries no Bun or SQLite import.
export * from "./pure/index.ts";
export {
  buildReachability,
  type ReachabilityBuildOptions,
  type ReachabilityVerification,
  reachabilityNotice,
  verifyReachability,
} from "./reachability.ts";
export {
  AUTHORITY_REPLAY_BYTES_PER_OPEN,
  AUTHORITY_REPLAY_CURSOR,
  AUTHORITY_REPLAY_ROWS_PER_OPEN,
  AUTHORITY_REPLAY_THREADS_PER_OPEN,
  needsAuthorityReplay,
  replayAtoms,
  replayAtomsBounded,
} from "./replay.ts";
export { ftsQuery } from "./rows.ts";
export {
  ATOM_NAME_REBUILD,
  ATTACHMENT_NAME_REBUILD,
  AUTHORITY_REPLAY,
  COUNTERS,
  MIGRATIONS,
} from "./schema.ts";
export {
  buildSemanticReceipt,
  DEFAULT_SEMANTIC_UNAVAILABLE_REASON,
  probeSemanticCapability,
  type SemanticCapability,
  type SemanticHit,
  type SemanticHitVerification,
  semanticPageRecord,
  verifySemanticHit,
  verifySemanticHits,
} from "./semantic.ts";
export {
  openKernelSemanticRuntime,
  prepareSemanticSqlite,
  SEMANTIC_BACKFILL_EPISODES,
  SEMANTIC_MANIFEST_SCHEMA,
  SEMANTIC_MAX_SPANS_PER_EPISODE,
  SEMANTIC_SPAN_BYTES,
  type SemanticBootstrap,
  type SemanticIndexPlan,
  type SemanticResourcePaths,
  semanticGenerationId,
  semanticIndexPlan,
  semanticRoleEligible,
} from "./semantic-kernel.ts";
export {
  type SemanticPhaseResolution,
  type SemanticSourcePhase,
  semanticEpistemic,
  semanticPhaseForSpan,
  semanticPhaseForSpanResolution,
} from "./semantic-phase.ts";
export {
  createSemanticRuntime,
  DEFAULT_SEMANTIC_MAX_BATCH,
  DEFAULT_SEMANTIC_MAX_CANDIDATES,
  DEFAULT_SEMANTIC_MAX_SPAN_BYTES,
  DEFAULT_SEMANTIC_TABLE_PREFIX,
  ensureSemanticDurableTables,
  probeSemanticRuntime,
  removeSemanticMetadata,
  SEMANTIC_RESOURCES,
  SEMANTIC_RUNTIME_IDENTITY,
  SEMANTIC_RUNTIME_SCHEMA_VERSION,
  type SemanticDurableRemoval,
  type SemanticIndexBatchResult,
  type SemanticIndexRejection,
  type SemanticIndexSpan,
  type SemanticRemoveResult,
  type SemanticRuntime,
  type SemanticRuntimeIdentity,
  type SemanticRuntimeOpenResult,
  type SemanticRuntimeOptions,
  type SemanticRuntimeProbe,
  type SemanticSearchOptions,
  unavailableSemanticRuntime,
} from "./semantic-runtime.ts";
export { stats } from "./stats.ts";
export {
  handoff,
  PROVIDER_OUTPUT_LIMIT_CODE,
  PROVIDER_ROUND_OUTPUT_BYTES,
  PROVIDER_TURN_OUTPUT_BYTES,
  type Provider,
  type ProviderEvent,
  type ProviderRequest,
  type RunTurnOptions,
  roundsDigest,
  runTurn,
  type TurnResult,
} from "./turn.ts";
export {
  ATOM_NAME_MIGRATION_BYTES_PER_OPEN,
  ATOM_NAME_MIGRATION_CURSOR,
  ATOM_NAME_MIGRATION_ROWS_PER_OPEN,
  ATOM_NAME_MIGRATION_THREADS_PER_OPEN,
  ATTACHMENT_NAME_MIGRATION_CURSOR,
  ATTACHMENT_NAME_MIGRATION_ROWS_PER_OPEN,
  ATTACHMENT_NAME_MIGRATION_THREADS_PER_OPEN,
  CHECKPOINT_EVERY,
  COMPILER_VERSION,
  chainRecord,
  checkedBudget,
  checkedModel,
  type EpisodeInput,
  metaHashOf,
  openVault,
  PACKET_MESSAGE_RETENTION,
  type PacketSummary,
  phaseCounter,
  pylosHome,
  type StoredCapsule,
  type ThreadProvenance,
  type Tombstone,
  Vault,
  VaultError,
  type VaultOptions,
} from "./vault.ts";
export { type VerifyResult, verify } from "./verify.ts";
