/**
 * The swap point.
 *
 * `src/aperture/kernel-impl.ts` is a one-line selector, regenerated by
 * `scripts/link-kernel.ts` before every build:
 *   • it points at `@pylos/core/pure` when `packages/core/src/pure/index.ts`
 *     exists — the real tokenizer, names(), extractive writer, ledger math and
 *     budget allocation that the desktop app runs;
 *   • at `src/sim/kernel.ts` otherwise.
 *
 * Whichever module arrives is checked against the surface the aperture needs.
 * If anything is missing the local simulation is used instead, and the page
 * says so out loud — a landing page for Pylos does not get to hide what it
 * substituted.
 */

import * as fallback from "../sim/kernel";
import { IMPL as candidate } from "./kernel-impl";

export type PureKernel = typeof fallback;

const REQUIRED = [
  "countTokens",
  "names",
  "namesWithSpans",
  "sealLeaf",
  "sealParent",
  "compile",
  "routeByLedger",
  "ledgerDigest",
  "classify",
  "atomLine",
  "LEAF_SIZE",
  "FAN_OUT",
] as const;

function usable(mod: unknown): mod is PureKernel {
  if (!mod || typeof mod !== "object") return false;
  const m = mod as Record<string, unknown>;
  for (const k of REQUIRED) {
    const v = m[k];
    if (v === undefined || v === null) return false;
  }
  return typeof m.LEAF_SIZE === "number" && typeof m.FAN_OUT === "number";
}

const picked = usable(candidate) ? candidate : fallback;

export const K: PureKernel = picked as PureKernel;

/** `"core"` when the real compiler is running; `"sim"` when the stand-in is. */
export const ENGINE: "core" | "sim" = picked === fallback ? "sim" : "core";

export const ENGINE_LABEL = ENGINE === "core" ? "@pylos/core · pure" : "local simulation · same rules";

export type {
  Capsule,
  CapsuleAtomLine,
  Episode,
  LossEntry,
  Packet,
  PageRecord,
  Slot,
} from "../sim/kernel";
