#!/usr/bin/env bun
/**
 * Compiles the server (and `@pylos/core` when it exists) into the single binary
 * Tauri ships as a sidecar:
 *
 *   apps/desktop/src-tauri/binaries/pylos-<target-triple>
 */
import { existsSync } from "node:fs";
import { mkdir, rm, writeFile } from "node:fs/promises";
import { dirname, join, resolve } from "node:path";

const here = dirname(new URL(import.meta.url).pathname);
const serverRoot = resolve(here, "..");
const repoRoot = resolve(serverRoot, "..", "..");
const coreEntry = join(repoRoot, "packages", "core", "src", "index.ts");
const outDir = join(repoRoot, "apps", "desktop", "src-tauri", "binaries");

async function hostTriple(): Promise<string> {
  const override = process.env.PYLOS_TARGET_TRIPLE;
  if (override !== undefined && override.length > 0) return override;
  try {
    const proc = Bun.spawn(["rustc", "-vV"], { stdout: "pipe", stderr: "ignore" });
    const text = await new Response(proc.stdout).text();
    const match = /^host:\s*(\S+)$/m.exec(text);
    if (match?.[1] !== undefined) return match[1];
  } catch {
    // rustc is optional; fall through to the platform default.
  }
  const arch = process.arch === "arm64" ? "aarch64" : "x86_64";
  if (process.platform === "darwin") return `${arch}-apple-darwin`;
  if (process.platform === "linux") return `${arch}-unknown-linux-gnu`;
  return `${arch}-pc-windows-msvc`;
}

async function main(): Promise<void> {
  const triple = await hostTriple();
  await mkdir(outDir, { recursive: true });
  const outfile = join(outDir, `pylos-server-${triple}`);

  const hasCore = existsSync(coreEntry);
  let entry = join(serverRoot, "src", "index.ts");
  let generated: string | undefined;

  if (hasCore) {
    // A static import is what makes the kernel bundleable into the binary.
    generated = join(serverRoot, ".sidecar-entry.ts");
    await writeFile(
      generated,
      [
        "// Generated by scripts/build-sidecar.ts. Do not edit.",
        'import * as core from "@pylos/core";',
        'import { registerCore } from "./src/kernel.ts";',
        'import { main } from "./src/index.ts";',
        "registerCore(core as never);",
        "await main();",
        "",
      ].join("\n"),
      "utf8",
    );
    entry = generated;
  }

  process.stdout.write(
    `building sidecar → ${outfile}\n  kernel: ${hasCore ? "@pylos/core (static)" : "dev-stub (core not built yet)"}\n`,
  );

  const build = Bun.spawn(
    ["bun", "build", "--compile", "--minify", "--sourcemap", entry, "--outfile", outfile],
    { cwd: serverRoot, stdout: "inherit", stderr: "inherit" },
  );
  const code = await build.exited;
  if (generated !== undefined) await rm(generated, { force: true });
  if (code !== 0) {
    process.stderr.write(`sidecar build failed (exit ${code})\n`);
    process.exit(code);
  }
  await Bun.spawn(["chmod", "755", outfile]).exited;
  process.stdout.write(`sidecar ready: ${outfile}\n`);
}

await main();
